name: tests

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - dev
    types: 
      - opened
  workflow_dispatch:
jobs:
  tests:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
